Fix: Associate the  message of each Suggestion correction to each own MarkerCorrection
PowerShell/PowerShellEditorServices pull request #1749
Opened 2022-03-30 20:13 UTC by bergmeister

With the recent fix in PR #1718, PSES processes now all Correction objects from PSSA but the message specifically was just taken from the last correction [here](https://github.com/PowerShell/PowerShellEditorServices/blob/e555dc050d3ef36272ba6f84925086cb7abc048a/src/PowerShellEditorServices/Services/TextDocument/ScriptFileMarker.cs#L150)

Related: https://github.com/PowerShell/PSScriptAnalyzer/pull/1782
Proof here that the message of each correction is associated to it as well (the actual code fix already was)

Before: 
![image](https://user-images.githubusercontent.com/9250262/160922634-06e98358-3970-424e-8c51-81bc861b239e.png)

AFTER
![image](https://user-images.githubusercontent.com/9250262/160921940-6e0c49a1-6d7a-41d3-a15a-a0cdf6d903e2.png)

2022-03-30 20:50 UTC, andschwa requested changes
Everything looks good, just one recurring test value. Some collection is coming through `null` and something isn't happy about it 😅 Thank you for working on this, excited to get it in!

2022-03-30 20:50 UTC, andschwa commented on src/PowerShellEditorServices/Services/Analysis/AnalysisService.cs
> +                if (marker.Corrections != null)
```suggestion
                if (marker.Corrections is not null)
```

2022-03-30 20:50 UTC, andschwa commented on src/PowerShellEditorServices/Services/TextDocument/ScriptFileMarker.cs
> +                                endOffset: -1),
```suggestion
                        Edit = new ScriptRegion(
                                diagnosticRecord.ScriptPath,
                                suggestedCorrection.Text,
                                startLineNumber: suggestedCorrection.StartLineNumber,
                                startColumnNumber: suggestedCorrection.StartColumnNumber,
                                startOffset: -1,
                                endLineNumber: suggestedCorrection.EndLineNumber,
                                endColumnNumber: suggestedCorrection.EndColumnNumber,
                                endOffset: -1),
```

2022-03-30 21:49 UTC, bergmeister commented
Yes, saw the test failure only after I opened the PR. Somehow, I cannot run the test with VS2022 with test explorer, can you give me some tips how I can run it locally to figure out why the value ends up being null by attaching the debugger and stepping through. Also happy to use VS Code instead alternatives

2022-03-31 00:32 UTC, andschwa commented
I exclusively use the C# extension in VS Code, it adds a "Run Test" and "Debug Test" code lens to each unit test, and it works great!

2022-03-31 22:35 UTC, andschwa commented
Good catch!

2022-03-31 22:38 UTC, andschwa approved these changes

2022-03-31 22:38 UTC, merged

2022-08-06 03:29 UTC, andschwa commented
Hey @bergmeister, I've added a PSSA test suite, what do you think a regression test for this would look like? See: https://github.com/PowerShell/PowerShellEditorServices/blob/main/test/PowerShellEditorServices.Test/Services/Symbols/PSScriptAnalyzerTests.cs