Fix up extension API
PowerShell/PowerShellEditorServices pull request #2053
Opened 2023-08-17 02:11 UTC by andyleejordan

Receive a `EditorOperationResponse` (not yet otherwise used). Delete dead code. Add optional `content` parameter to `NewFile`. Expose `CloseFile` and `SaveFile`. Fix an outdated warning message.

Part of https://github.com/PowerShell/vscode-powershell/pull/4703 so I could test it.

2023-08-17 19:58 UTC, andyleejordan commented
Tested that last commit with a temporary multi-root workspace:

```
> $pseditor.GetEditorContext().CurrentFile.WorkspacePath
mocks/BinaryModule/BinaryModuleTest.ps1
@andyjordane318 ...src/vscode-powershell/test/mocks andyleejordan/fix-newfile-casing ≡ +0 ~1 -0 !
> $pseditor.GetEditorContext().CurrentFile.WorkspacePath
features/CustomViews.test.ts
@andyjordane318 ...src/vscode-powershell/test/mocks andyleejordan/fix-newfile-casing ≡ +0 ~1 -0 !
> $pseditor.GetEditorContext().CurrentFile.WorkspacePath
untitled:Untitled-1
```

2023-08-22 18:19 UTC, SeeminglyScience requested changes
Just a couple of changes so we don't introduce binary breaking changes, other than that LGTM

2023-08-22 18:58 UTC, andyleejordan commented on src/PowerShellEditorServices/Extensions/EditorWorkspace.cs
> +        /// <param name="content">The content to place in the new file.</param>
But how? If it's used with no arguments, it gets its default argument.

2023-08-22 20:06 UTC, SeeminglyScience commented on src/PowerShellEditorServices/Extensions/EditorWorkspace.cs
> +        public void NewFile(string content = "") => editorOperations.NewFileAsync(content).Wait();
```suggestion
```

think the previous suggestion bugged out (or I did it wrong)

2023-08-22 20:09 UTC, SeeminglyScience commented on src/PowerShellEditorServices/Services/Extension/EditorOperationsService.cs
> +        public async Task NewFileAsync(string content = "")
```suggestion
        public async Task NewFileAsync() => NewFileAsync(string.Empty);

        public async Task NewFileAsync(string content)
```

2023-08-22 20:16 UTC, SeeminglyScience approved these changes
LGTM! ❤️

2023-08-22 20:57 UTC, merged