Show errors from PSScriptAnalyzer and other operations when -EnableConsoleRepl:$false
PowerShell/PowerShellEditorServices pull request #2122
Opened 2023-12-26 11:33 UTC by dkattan

# PR Summary

Meaningful output from PSES's internal PowerShell is suppressed if you don't specify -EnableConsoleRepl.

## PR Context

I'd like to be able to see the output from PSScriptAnalyzer but my application has a read-only terminal. 
This SwitchParameter prevents the UI from being set to NullPSHostUI without enabling Repl functionality.

Perhaps a better way to implement this would be to condition off the use of named pipes as I believe the intention of the following code is to prevent clobbering stdio since ConsoleRepl can only be used when connecting via named pipes.

```csharp
     UI = hostInfo.ConsoleReplEnabled || hostInfo.UseCurrentPSHostUI
                ? new EditorServicesConsolePSHostUserInterface(loggerFactory, hostInfo.PSHost.UI)
                : new NullPSHostUI();
```

2024-01-03 18:23 UTC, andyleejordan commented on src/PowerShellEditorServices/Services/Analysis/PssaCmdletAnalysisEngine.cs
> +                // * PSScriptAnalyzer not being able to find its PSScriptAnalyzer.psd1 because we are hosted by an Assembly other than pwsh.exe
Ooooh

2024-01-03 18:26 UTC, andyleejordan requested changes
I like quite a bit of this but would want to clean it up a bit, put it through some thorough testing, and I think you are quite right that we should condition this based on named pipes instead of adding (yet another) parameter to the startup script. Let me know if you want to do some of that, and please tell me about the best way to go about testing this!

2024-01-03 23:48 UTC, dkattan commented
> I like quite a bit of this but would want to clean it up a bit, put it through some thorough testing, and I think you are quite right that we should condition this based on named pipes instead of adding (yet another) parameter to the startup script. Let me know if you want to do some of that, and please tell me about the best way to go about testing this!

Sweet, I'll go ahead and make that change

2024-01-04 14:21 UTC, dkattan commented
> please tell me about the best way to go about testing this!

This is going to be hard to test since it appears that all the tests use Stdio, unless I’m mistaken.

2024-02-12 21:48 UTC, andyleejordan approved these changes

2024-02-12 23:24 UTC, andyleejordan commented
That CI failure was a red herring, it was actually caused by GitHub Actions giving us a mix of PowerShell versions leading to a missed bug in a unit test, fixed by https://github.com/PowerShell/PowerShellEditorServices/pull/2135

2024-02-13 00:24 UTC, merged