Initial Pass that implements DebugAdapterServerTestBase
PowerShell/PowerShellEditorServices pull request #2208
Opened 2024-12-05 02:11 UTC by JustinGrote

# PR Summary

## PR Context

2024-12-05 07:14 UTC, JustinGrote commented
@andyleejordan @SeeminglyScience Did a lot of cleanup here, DAP tests run much faster and I should have cleaned up the race conditions, they've been completely reliable for me so far. The tests should also read fairly cleaner now as well.

2024-12-10 19:28 UTC, andyleejordan commented
@JustinGrote running this through the internal pipeline right now!

2024-12-10 19:51 UTC, andyleejordan commented
> @JustinGrote running this through the internal pipeline right now!

Sooo actually per 20fa478dcd61bf75c84fe69f2f3f17ea4233d2e0 we cannot currently run the tests on OneBranch since it's stuck with PowerShell 7.3...so this will have to wait until January 😵

2025-02-26 22:11 UTC, andyleejordan commented
Hi @JustinGrote, we can _finally_ run the tests again in ADO. Would you want to get this PR updated? Note that I had to skip the `getCommand` test, it just hung (@SeeminglyScience's guess was that the ADO PowerShell might have network shares in `PSModulePath` but yeah it just ran for twenty minutes before I killed it).

2025-02-28 00:30 UTC, JustinGrote commented
@andyleejordan rebased and passed locally for me. Lets see if ADO likes it.
![image](https://github.com/user-attachments/assets/3c339cfe-bf79-4e14-80ea-18c452719aa7)

2025-02-28 00:47 UTC, JustinGrote commented
Looks like it works. I can do the logging fixups as a separate item especially now that the other logging stuff was implemented.

2025-02-28 02:12 UTC, JustinGrote commented on test/PowerShellEditorServices.Test.E2E/DebugAdapterProtocolMessageTests.cs
> +            return nextLine;
Thanks copilot, but it's just a test.

2025-03-04 21:04 UTC, JustinGrote commented on test/PowerShellEditorServices.Test.E2E/Hosts/PsesStdioLanguageServerProcessHost.cs
> +    private static readonly string[] s_featureFlags = { "PSReadLine" };
I just looked and I didn't see this feature flag actually referenced anywhere, so it can probably be removed but I think that should be the scope of another PR.

2025-03-04 21:05 UTC, JustinGrote commented on test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
>              Skip.If(IsLinux, "This depends on the help system, which is flaky on Linux.");
Maybe not? As you said lets YOLO it as a test.

2025-03-04 21:06 UTC, JustinGrote commented on test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
>              Skip.If(IsLinux, "This depends on the help system, which is flaky on Linux.");
I also think I separately fixed this test in the other branch so there might be a conflict, I'll rebase.

2025-03-04 21:07 UTC, JustinGrote commented on test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
>                  "Windows PowerShell doesn't trust PSScriptAnalyzer by default so it won't load.");
It might be! Maybe I can get some LSP trace logs from them and stick in some telemetry to find out.

2025-03-04 23:09 UTC, JustinGrote commented on test/PowerShellEditorServices.Test.E2E/PowerShellEditorServices.Test.E2E.csproj
> +    <Content Include="..\PowerShellEditorServices.Test.Shared\PSHelp\**\*"
Only if the tests use Microsoft.PowerShell.Utility cmdlets for their reference. This is only required for Windows PowerShell since it doesn't ship this help in-box, all pwsh flavors do ship help in-box and so we don't have to do this. Assuming we find/adjust all help-based tests to use Microsoft.PowerShell.Utility, then yes this should fix them in AzDO CI

2025-03-04 23:55 UTC, JustinGrote commented on test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
>              Skip.If(Environment.GetEnvironmentVariable("TF_BUILD") is not null,
It is super slow still in GH CI, since it is fetching *all* commands. I'll put it back into skip but we may want to see if it at least completes on non WinPS in ADO sometime.

2025-03-05 01:24 UTC, andyleejordan commented
LMAO Windows is mad now, sorry.

2025-03-05 03:03 UTC, JustinGrote commented
@andyleejordan  I'm not done fixing it, I'll flip it back to draft for now

2025-03-05 23:21 UTC, JustinGrote commented
@andyleejordan the `FindSymbolsInDSCFile` test failure appears to be because of 0135baaf8d6c118457867ac7481a74d067a2426a #1984. You updated the IDs of DSC symbols to include a prefix, but the test doesn't check for that new prefix.
https://github.com/PowerShell/PowerShellEditorServices/blob/de0eea18e8ce509915e8fdd8faeae0e2993c40c8/src/PowerShellEditorServices/Services/Symbols/Visitors/SymbolVisitor.cs#L275-L276

I will "fix" this test but please confirm if you're expecting something else. Also, completions allow for a `sortText` property in the LSP, maybe we should implement this more explicitly if that's the intention for the prefix?

2025-03-06 00:50 UTC, JustinGrote commented
@andyleejordan I came up with a better way to do the "offline" help update in eaeefa13f017d94bd9ad417ce6e72c406b29f874 and centralized it in the build script again.

2025-03-06 05:47 UTC, andyleejordan commented
> @andyleejordan the `FindSymbolsInDSCFile` test failure appears to be because of [0135baa](https://github.com/PowerShell/PowerShellEditorServices/commit/0135baaf8d6c118457867ac7481a74d067a2426a) #1984. You updated the IDs of DSC symbols to include a prefix, but the test doesn't check for that new prefix.
> 
> https://github.com/PowerShell/PowerShellEditorServices/blob/de0eea18e8ce509915e8fdd8faeae0e2993c40c8/src/PowerShellEditorServices/Services/Symbols/Visitors/SymbolVisitor.cs#L275-L276
> 
> I will "fix" this test but please confirm if you're expecting something else. Also, completions allow for a `sortText` property in the LSP, maybe we should implement this more explicitly if that's the intention for the prefix?

Oops. I don't think I'm expecting something else. And if I remember correctly on the sortText, VS Code completely ignored it and applies their own sorting.

2025-03-06 21:19 UTC, JustinGrote commented
@andyleejordan this should be ready for re-review. Changes summary:
1. Fixed help-based tests to all use `Microsoft.PowerShell.Archive`, because it has a small help file to be vendored into the codebase
1. Added update help build script for all pwsh platforms with verify check.
1. Added `upterm` to the CI process pre-build. This allows, if you explicitly re-run a job with debug build, to be able to SSH into the runner to interactively troubleshoot/debug issues. Only runs on debug re-runs
1. Most tests conditional on platforms fixed or mitigated.

2025-03-18 17:03 UTC, andyleejordan requested changes
Sorry I was being picky about my build script lol, going to commit these, test, and merge!

2025-03-18 17:04 UTC, andyleejordan approved these changes

2025-03-18 17:05 UTC, andyleejordan commented
That's what I get for doing this on GitHub.

2025-03-18 17:09 UTC, andyleejordan commented
It was because I added a single quote...inside single quotes 🫨

2025-03-18 17:18 UTC, merged

2025-03-18 17:39 UTC, JustinGrote commented on .github/workflows/ci-test.yml
> +        uses: lhotari/action-upterm@v1
I'm working on a version that lets you vscode remote into the github action, the tricky part is the authentication but it's definitely doable :)

2025-03-18 17:40 UTC, JustinGrote commented
@andyleejordan  thank you!